---
 - name: update repository and install packages 
   become_method: sudo
   become_user: root
   tasks:
   - name: update packages
     apt:
       name: '*'
       state: latest
   - name: install packages
     apt:
       name: "{{ package }}"
     vars:
       package:
          - procs
          - htop
          - mc
          - iotop
          - tree
          - tmux
          - tar
          - wget
        state: present
