---
 - name: update repository and install packages 
   become: true
   become_user: root
   apt: pkg={{ item }}
     update_cache: true
     cache_valid_time: 3600
     force_apt_get: true      
     state: present
     with_items:
        - procs
        - htop
        - mc
        - iotop
        - tree
        - tmux
