all:
  hosts:
    monitoring.project.domain: 89.208.85.81
    app02.project.domain: 185.241.192.50
    app01.project.domain: 5.188.142.6
    rrdns.project.domain: 146.185.243.121
    mysql_master: 87.239.109.35
  children:
    webservers:
      hosts:
        app02.project.domain: 10.0.1.37
        app01.project.domain: 10.0.1.20
    mysql:
      hosts:
        mysql_master: 10.0.1.4
    monitoring:
      hosts:
         monitoring.project.domain: 10.0.1.10
