all:
  hosts:
    monitoring.project.domain: 5.188.142.6
    app02.project.domain: 5.188.141.58
    app01.project.domain: 185.241.192.50
    rrdns.project.domain: 5.188.142.6
    mysql_master: 87.239.109.35
  children:
    webservers:
      hosts:
        app02.project.domain: 10.0.22.2
        app01.project.domain: 10.0.11.2
    nginx:
      hosts:
        nginx01.project.domain: 10.0.11.3
        nginx02.project.domain: 10.0.22.3
