---
- name: Enable 80,443 and 22 port- firewalld
  become_method: sudo
  become_user: root

  tasks:
  - name: enable 80 port
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: enabled
  - name: enable 443 port
    ansible.posix.firewalld:
      service: https
      permanent: yes
      state: enabled
  - name: enable 22 port
    ansible.posix.firewalld:
      service: ssh
      permanent: yes
      state: enabled   
  - name: restart service firewalld
    ansible.builtin.service:
      name: firewalld
      state: restarted
