---
- name: reboot servers
  become_method: sudo
  become_user: root

  tasks:
  - name: rebooting hosts and waiting for them to reboot
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
