---
- name: Install unison
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - unison
    - unison-all
    - cron

- name: enable cron
  action: service name=cron state=started
### path /var/www/wordpress

- name: Create a directory if it does not exist
  become: True
  ansible.builtin.file:
    path: ~/.unison
    state: directory
    mode: '0755'

- name: update unison/default.prf
  become: True
  template:
    src: default.prf
    dest: ~/.unison/default.prf

- name: Copy file
  become: True
  ansible.builtin.copy:
    content: '#!/bin/bash/ \n unison /var/www/wordpress ssh://127.0.0.1//var/www/wordpress'
    dest: /usr/local/bin/unisonsync.sh
    owner: test
    group: test
    mode: '0755'

- name: Performs synchronization every 5 minutes
  ansible.builtin.cron:
    name: unisonsync
    minute: "*/5"
    user: ubuntu
    job: "/usr/local/bin/unisonsync.sh"
