---
- name: wget nginx for building
  get_url:
    url: "http://nginx.org/download/nginx-1.18.0.tar.gz"
    dest: "/usr/src/nginx-1.18.0.tar.gz"
    
- name: unpack nginx-vts module
  become: yes
  ansible.builtin.unarchive:
    src: /usr/src/nginx-1.18.0.tar.gz
    dest: /usr/src
    remote_src: yes
    
- name: git nginx-vts
  ansible.builtin.git:
    repo: 'https://github.com/vozlt/nginx-module-vts.git'
    dest: /usr/src/nginx-module-vts
    
- name: apt libpcre3-dev for make install nginx
  apt:
    name: libpcre3-dev
    
- name: install nginx config
  become: yes
  template:
    src: nginx.config.j2
    dest: /etc/nginx/nginx.conf

- name: Disable default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: make install nginx-vts
  become: yes
  shell: "cd /usr/src/nginx-1.18.0 &&
   ./configure \
       --prefix=/etc/nginx \
       --sbin-path=/usr/sbin/nginx \
       --modules-path=/usr/lib/nginx/modules \
       --conf-path=/etc/nginx/nginx.conf \
       --error-log-path=/var/log/nginx/error.log \
       --http-log-path=/var/log/nginx/access.log \
       --pid-path=/var/run/nginx.pid \
       --lock-path=/var/run/nginx.lock \
       --http-client-body-temp-path=/var/cache/nginx/client_temp \
       --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
       --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
       --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
       --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
       --user=nginx \
       --group=nginx \
       --with-http_ssl_module \
       --with-http_realip_module \
       --with-http_addition_module \
       --with-http_sub_module \
       --with-http_dav_module \
       --with-http_flv_module \
       --with-http_gunzip_module \
       --with-http_gzip_static_module \
       --with-http_random_index_module \
       --with-http_secure_link_module \
       --with-http_stub_status_module \
       --with-http_auth_request_module \
       --with-threads --with-stream \
       --with-stream_ssl_module \
       --with-http_slice_module \
       --with-mail \
       --with-mail_ssl_module \
       --with-file-aio \
       --with-http_v2_module \
       --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' \
       --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed' \
       --add-module=/usr/src/nginx-module-vts &&
   make &&
   make install && cp objs/ngx_http_vhost_traffic_status_module.so /etc/nginx/modules &&
   chmod 644 /etc/nginx/modules"
  
- name: Create a directory /var/cache/nginx/client_temp
  ansible.builtin.file:
    path: /var/cache/nginx/client_temp
    state: directory
    mode: '0755'
  notify:
    - restart nginx