---
- name: установка стандартных утилит
  hosts: all
  become: yes
  vars:
    node_exporter_version: 1.1.2
    grafana_admin_password: admin
  roles:
    - default_packages
    - access
    - firewall
    - node_exporter
    - prometheus
    - grafana

