---
- name: установка стандартных утилит на все сервера
  hosts: all
  become: yes
  vars:
    node_exporter_version: 1.1.2
    grafana_admin_password: admin
  roles:
    - default_packages
    - access
    - firewall
    - node_exporter

- name: настройка сервера мониторинга
  hosts: monitoring
  vars:
    grafana_admin_password: admin
  roles:
    - prometheus
    - grafana

- name: установка wordpress
  hosts: webservers
  become: yes
  vars:
    - download_url: "http://wordpress.org/latest.tar.gz"
  roles:
    - nginx
    - nginx_vts
    - php5
    - wordpress
#    - nginx_exporter

- name: установка nginx
  hosts: load_balancer
  become: yes
  roles:
    - nginx
    - nginx_vts